#!/bin/sh

# Use the "logo" key as the primary modifier
mod="Mod4"

# Normal mode applications
riverctl map normal $mod Return          spawn kitty
riverctl map normal $mod B               spawn "kitty btop"
riverctl map normal $mod V               spawn "kitty ncmpcpp"
# riverctl map normal $mod D               spawn "fuzzel -r 0 -b 151510ff -t d2cad3ff -s 6691d2ff -C aa3c9fff -m a52e4dff -w 40 -l 12 -B 2"
riverctl map normal $mod D               spawn "albert show"
riverctl map normal $mod+Control Space   spawn "fnottctl dismiss"
riverctl map normal None Print           spawn wl-screenshot

riverctl map normal $mod Space           spawn "pkill -USR1 waybar"

# Mod+Q to close the focused view
riverctl map normal $mod Q close

# Mod+Shift+Q to exit river
riverctl map normal $mod+Shift Q exit

# Mod+J and Mod+K to focus the next/previous view in the layout stack
riverctl map normal $mod J focus-view next
riverctl map normal $mod K focus-view previous

# Mod+Shift+J and Mod+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal $mod+Shift J swap next
riverctl map normal $mod+Shift K swap previous

# Mod+Period and Mod+Comma to focus the next/previous output
riverctl map normal $mod Period focus-output next
riverctl map normal $mod Comma focus-output previous

# Mod+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal $mod+Shift Period send-to-output next
riverctl map normal $mod+Shift Comma send-to-output previous

# Mod+Return to bump the focused view to the top of the layout stack
riverctl map normal $mod Tab zoom

# Mod+H and Mod+L to decrease/increase the main_factor value of rivercarro by 0.05
riverctl map normal $mod H send-layout-cmd rivercarro "main-ratio -0.05"
riverctl map normal $mod L send-layout-cmd rivercarro "main-ratio +0.05"

# Mod+Shift+H and Mod+Shift+L to increment/decrement the main_count value of rivercarro.
riverctl map normal $mod+Shift H send-layout-cmd rivercarro "main-count +1"
riverctl map normal $mod+Shift L send-layout-cmd rivercarro "main-count -1"

# Mod + Left Mouse Button to move views
riverctl map-pointer normal $mod BTN_LEFT move-view

# Mod + Right Mouse Button to resize views
riverctl map-pointer normal $mod BTN_RIGHT resize-view

for i in $(seq 1 9)
do
    tags=$((1 << (i - 1)))

    # Mod+[1-9] to focus tag [0-8]
    riverctl map normal $mod "$i" set-focused-tags $tags

    # Mod+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal $mod+Shift "$i" set-view-tags $tags

    # Mod+Ctrl+[1-9] to toggle focus of tag [0-8]
    riverctl map normal $mod+Control "$i" toggle-focused-tags $tags

    # Mod+Shift+Ctrl+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal $mod+Shift+Control "$i" toggle-view-tags $tags
done

# Mod+0 to focus all tags
# Mod+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal $mod 0 set-focused-tags $all_tags
riverctl map normal $mod+Shift 0 set-view-tags $all_tags

# Mod+S to toggle float
riverctl map normal $mod S toggle-float

# Mod+F to toggle fullscreen
riverctl map normal $mod F toggle-fullscreen

# Mod+{Up,Right,Down,Left} to change layout orientation
riverctl map normal $mod Up    send-layout-cmd rivercarro "main-location top"
riverctl map normal $mod Right send-layout-cmd rivercarro "main-location right"
riverctl map normal $mod Down  send-layout-cmd rivercarro "main-location bottom"
riverctl map normal $mod Left  send-layout-cmd rivercarro "main-location left"

# Monocle mode
riverctl map normal $mod M     send-layout-cmd rivercarro "main-location monocle"

# Passthrough mode
riverctl declare-mode passthrough
riverctl map normal $mod G enter-mode passthrough
riverctl map passthrough $mod G enter-mode normal

# Mappings for all modes
for mode in normal locked
do
    riverctl map $mode None XF86AudioRaiseVolume  spawn "pamixer -i 1"
    riverctl map $mode None XF86AudioLowerVolume  spawn "pamixer -d 1"
    riverctl map $mode None XF86AudioMute         spawn "pamixer -t"

    riverctl map $mode None XF86AudioPrev     spawn "mpc prev"
    riverctl map $mode None XF86AudioNext     spawn "mpc next"
    riverctl map $mode None XF86AudioPlay     spawn "mpc toggle"
done

# Set background and border color
riverctl background-color 0x151510
riverctl border-color-focused 0xc29dd5
riverctl border-color-unfocused 0x6691d2
riverctl border-width 1

riverctl attach-mode bottom

# Set input stuff
riverctl set-repeat 50 300
riverctl set-cursor-warp on-output-change
for pad in $(riverctl list-inputs | grep -i touchpad)
do
  riverctl input $pad events enabled
  riverctl input $pad tap enabled
done

# Set app-ids of views which should float
riverctl float-filter-add app-id "float"
riverctl float-filter-add app-id "popup"

# Run applications
systemctl --user import-environment WAYLAND_DISPLAY DISPLAY DBUS_SESSION_BUS_ADDRESS XDG_SESSION_TYPE XDG_CURRENT_DESKTOP
dbus-update-activation-environment WAYLAND_DISPLAY
systemctl --user start graphical-session.target

xrdb ~/.Xresources

waybar &
fnott &
oguri &

systemctl --user restart mpdris2.service

# Jump to rivercarro
riverctl default-layout rivercarro
exec rivercarro -inner-gaps 0 -outer-gaps 0
