#!/usr/bin/env bash
set -eo pipefail

# --- utility functions ---
# echo to stderr
function ercho { printf "%s\n" "$*" >&2; }

# shortcut to return values
function r { printf "%s" "$*"; }

# sleep that counts
function visible_sleep {
    local DELAY=$1

    for i in $(seq "$DELAY" -1 1); do
        for s in / - \\ \|; do
            printf "\r%s = $i        " "$s"
            sleep 0.25
        done
    done
    printf "\r                \r"
}

# prompt user for y or n
function yes_or_no {
    local RETURN=0

    if [[ -n "$ALWAYS_YES" ]]; then
        return "$RETURN"
    fi

    local yn
    read -r -p "$* [Y/n]: " yn
    case $yn in
        [Yy]*) RETURN=0 ;;
        [Nn]*) RETURN=1 ;;
    esac

    return "$RETURN"
}

# retry with exponential backoff
function retry {
    local max="$1"
    shift 1

    local delay=1
    local attempts=1

    while [[ "$attempts" -le "$max" ]]; do
        if "$@"; then
            break
        fi

        if [[ "$attempts" -lt "$max" ]]; then
            echo "Retrying in $delay seconds..."
            visible_sleep "$delay"
        elif [[ "$attempts" -eq "$max" ]]; then
            echo "Failed after $attempts attempts"
            return 1
        fi

        attempts=$((attempts + 1))
        delay=$((delay * 2))
    done
}

# --- script helper functions ---
FLK="$(nix eval --impure .#planets --json --apply 'with import <nixpkgs> {}; lib.attrsets.filterAttrsRecursive (n: v: n != "core")')"

# gets planets from flake
function get_planets {
    jq -c -r 'keys' <<< "$FLK"
}

# gets moons for a planet
function get_moons {
    local planet=$1
    jq -c -r ".\"$planet\".moons | keys" <<< "$FLK"
}

# gets trajectory for a moon
function get_trajectory {
    local planet=$1
    local moon=$2
    jq -c -r ".\"$planet\".moons.\"$moon\".trajectory" <<< "$FLK"
}

# gets orbits for a moon
function get_orbits {
    local planet=$1
    local moon=$2
    jq -c -r ".\"$planet\".moons.\"$moon\".orbits" <<< "$FLK"
}

# checks if planet exists
function has_planet {
    local planet=$1
    if [[ "$(jq -e "has(\"$planet\")" <<< "$FLK" )" == "false" ]]; then
        return 1
    else
        return 0
    fi
}

# checks if a moon exists for a planet
function has_moon {
    local planet=$1
    local moon=$2
    if [[ "$(jq -e ".\"$planet\".moons | has(\"$moon\")" <<< "$FLK" )" == "false" ]]; then
        return 1
    else
        return 0
    fi
}

function get_satellites {
    local planet=$1
    local moon=$2
    jq -c -r ".\"$planet\".moons.\"$moon\".satellites" <<< "$FLK"
}

# builds an output for a moon in a planet
function build_moon_output {
    local planet=$1
    local moon=$2
    local output=$3

    # build
    local build_cmd="nix $NIX_EXTRA_OPTS build --log-format internal-json -v --no-link \".#planets.$planet.moons.$moon.core.$output\" |& nom --json"

    if eval "$build_cmd"; then
        nix path-info ".#planets.$planet.moons.$moon.core.$output"
        return 0
    else
        return 1
    fi
}

# sends satellites to a moon in a planet
function send_satellites_ {
    local trajectory_host=$1
    local trajectory_port=$2
    local dest_path=$3
    local path=$4
    local chown_target=$5

    echo "[solarsys] Deploying satellite: |$name| to destination: |$dest_path|"
    ssh -t "root@$trajectory_host" -p "$trajectory_port" "mkdir -p $(dirname "$dest_path")" 2> /dev/null
    rsync -q -e "ssh -p $trajectory_port" -r "$path" "root@[$trajectory_host]:$dest_path"

    if [[ -n "$chown_target" && ! "$chown_target" == "null" ]]; then
        echo "[solarsys] Chowning satellite: |$dest_path| to: |$chown_target|"
        ssh -t "root@$trajectory_host" -p "$trajectory_port" "chown $chown_target $dest_path" 2> /dev/null
    fi
}

function send_satellites {
    local planet=$1
    local moon=$2
    local trajectory_host=$3
    local trajectory_port=$4

    # parse satellites
    local satellites
    readarray -t satellites <<< "$(get_satellites "$planet" "$moon" | jq -c -r 'to_entries | .[]')"

    for satellite in "${satellites[@]}"; do
        local name
        name="$(jq -c -r '.key' <<< "$satellite")"

        local dest_path
        dest_path="$(jq -c -r '.value.destination' <<< "$satellite")"
        if [[ "$dest_path" == "null" ]]; then
            dest_path="/run/keys/$satellite"
        fi

        local path
        path="$(jq -c -r '.value.path' <<< "$satellite")"
        if [[ -n "$path" && ! "$path" == "null" ]]; then
            local chown_target
            chown_target="$(jq -c -r '.value.chown' <<< "$satellite")"

            send_satellites_ "$trajectory_host" "$trajectory_port" "$dest_path" "$path" "$chown_target" &
        fi
    done

    wait
}

# --- script main ---
# -- script main functions --
# deploys a single moon in a planet
function deploy {
    local planet=$1
    local moon=$2

    # sanity check
    if ! has_planet "$planet"; then
        ercho "error~ Planet: |$planet| does not exist!"
        return 1
    fi
    if ! has_moon "$planet" "$moon"; then
        ercho "error~ Moon: |$moon| does not exist for planet: |$planet|!"
        return 1
    fi

    echo "[solarsys] Deploying moon: |$moon| in planet: |$planet|"

    # check if we are deploying our current system
    if [[ "$moon" == "$(hostname)" ]]; then
        echo "[solarsys] Moon: |$moon| is the current system..."

        # wait for user response
        yes_or_no "[solarsys] Deploy?" || return

        # build and switch to new config
        local buildpath
        if buildpath="$(build_moon_output "$planet" "$moon" "config.system.build.toplevel")"; then
            echo "[solarsys] Press enter to continue..."
            read -r
            sudo bash <<EOF
nix-env -p /nix/var/nix/profiles/system --set "$buildpath"
"$buildpath"/bin/switch-to-configuration switch
EOF
        fi
    else # deploying remotely
        local trajectory
        trajectory="$(get_trajectory "$planet" "$moon")"

        if [[ -z "$(jq -c -r '.' <<< "$trajectory")" ]]; then
            ercho "warning~ Moon: |$moon| is set for a local trajectory, skipping."
            return
        fi

        local trajectory_host trajectory_port
        trajectory_host="$(jq -c -r '.host' <<< "$trajectory")"
        trajectory_port="$(jq -c -r '.port' <<< "$trajectory")"

        echo "[solarsys] Moon: |$moon| is at |$trajectory_host| on port |$trajectory_port|"

        # build config
        local buildpath
        if buildpath="$(build_moon_output "$planet" "$moon" "config.system.build.toplevel")"; then
            # copy built config
            NIX_SSHOPTS="-p $trajectory_port" nix copy --to "ssh://root@$trajectory_host" "$buildpath"
            # copy remote deploy script
            rsync -q -e "ssh -p $trajectory_port" "$(dirname "$0")/solarsys-remote.sh" "root@[$trajectory_host]:/tmp/solarsys-remote.sh"
            # send satellites
            send_satellites "$planet" "$moon" "$trajectory_host" "$trajectory_port"

            # deploy stage1 - testing config
            echo "[solarsys] Deploying & Testing Config"
            ssh -t "root@$trajectory_host" -p "$trajectory_port" "bash /tmp/solarsys-remote.sh d1 $buildpath" 2> /dev/null
            # wait to see if we can still connect
            echo "[solarsys] Waiting for reconnection..."
            retry 5 ssh -o ConnectTimeout=5 -q "root@$trajectory_host" -p "$trajectory_port" exit
            # deploy stage2 - real deploy
            echo "[solarsys] Deploying & Switching to Config"
            ssh -t "root@$trajectory_host" -p "$trajectory_port" "bash /tmp/solarsys-remote.sh d2 $buildpath" 2> /dev/null
            echo "[solarsys] Deployed moon: |$moon|"
        fi
    fi
}

# builds an output for a moon in a planet
function build {
    local planet=$1
    local moon=$2
    local output=$3

    # sanity check
    if ! has_planet "$planet"; then
        ercho "error~ Planet: |$planet| does not exist!"
        return 1
    fi
    if ! has_moon "$planet" "$moon"; then
        ercho "error~ Moon: |$moon| does not exist for planet: |$planet|!"
        return 1
    fi

    echo "[solarsys] Building output: |$output| for moon: |$moon| in planet: |$planet|"

    build_moon_output "$planet" "$moon" "$output"
}

# rolls back a moon in a planet
function rollback {
    local planet=$1
    local moon=$2

    # sanity check
    if ! has_planet "$planet"; then
        ercho "error~ Planet: |$planet| does not exist!"
        return 1
    fi
    if ! has_moon "$planet" "$moon"; then
        ercho "error~ Moon: |$moon| does not exist for planet: |$planet|!"
        return 1
    fi

    echo "[solarsys] Rolling back moon: |$moon| in planet: |$planet|"

    # check if we are testing our current system
    if [[ "$moon" == "$(hostname)" ]]; then
        echo "[solarsys] Moon: |$moon| is the current system..."

        # wait for user response
        yes_or_no "Rollback?" || return

        # rollback
        sudo bash <<EOF
nix-env -p /nix/var/nix/profiles/system --rollback
/nix/var/nix/profiles/system/bin/switch-to-configuration switch
EOF
    else # rolling back remotely
        local trajectory
        trajectory="$(get_trajectory "$planet" "$moon")"

        if [[ -z "$(jq -c -r '.' <<< "$trajectory")" ]]; then
            ercho "warning~ Moon: |$moon| is set for a local trajectory, skipping."
            return
        fi

        local trajectory_host trajectory_port
        trajectory_host="$(jq -c -r '.host' <<< "$trajectory")"
        trajectory_port="$(jq -c -r '.port' <<< "$trajectory")"

        echo "[solarsys] Moon: |$moon| is at |$trajectory_host| on port |$trajectory_port|"
    fi
}

# tests a single moon in a planet
function test_moon {
    local planet=$1
    local moon=$2

    # sanity check
    if ! has_planet "$planet"; then
        ercho "error~ Planet: |$planet| does not exist!"
        return 1
    fi
    if ! has_moon "$planet" "$moon"; then
        ercho "error~ Moon: |$moon| does not exist for planet: |$planet|!"
        return 1
    fi

    echo "[solarsys] Testing moon: |$moon| in planet: |$planet|"

    # check if we are testing our current system
    if [[ "$moon" == "$(hostname)" ]]; then
        echo "Moon: |$moon| is the current system..."

        # wait for user response
        yes_or_no "Test?" || return

        # build and test new config
        local buildpath
        if buildpath="$(build_moon_output "$planet" "$moon" "config.system.build.toplevel")"; then
            echo "[solarsys] Press enter to continue..."
            read -r
            sudo "$buildpath"/bin/switch-to-configuration test
        fi
    else # testing remotely
        local trajectory
        trajectory="$(get_trajectory "$planet" "$moon")"

        if [[ -z "$(jq -c -r '.' <<< "$trajectory")" ]]; then
            ercho "warning~ Moon: |$moon| is set for a local trajectory, skipping."
            return
        fi

        local trajectory_host trajectory_port
        trajectory_host="$(jq -c -r '.host' <<< "$trajectory")"
        trajectory_port="$(jq -c -r '.port' <<< "$trajectory")"

        echo "[solarsys] Moon: |$moon| is at |$trajectory_host| on port |$trajectory_port|"
    fi
}

# ssh to a moon in a planet
function ssh_moon {
    local planet=$1
    local moon=$2

    # sanity check
    if ! has_planet "$planet"; then
        ercho "error~ Planet: |$planet| does not exist!"
        return 1
    fi
    if ! has_moon "$planet" "$moon"; then
        ercho "error~ Moon: |$moon| does not exist for planet: |$planet|!"
        return 1
    fi

    # check if the moon we are trying to connect to is the current system
    if [[ "$moon" == "$(hostname)" ]]; then
        ercho "error~ Moon: |$moon| is the current system!"
    else
        local trajectory
        trajectory="$(get_trajectory "$planet" "$moon")"

        if [[ -z "$(jq -c -r '.' <<< "$trajectory")" ]]; then
            ercho "error~ Moon: |$moon| does not have a set trajectory!"
            return 1
        fi

        local trajectory_host trajectory_port
        trajectory_host="$(jq -c -r '.host' <<< "$trajectory")"
        trajectory_port="$(jq -c -r '.port' <<< "$trajectory")"

        echo "[solarsys] Moon: |$moon| is at |$trajectory_host| on port |$trajectory_port|"
        exec ssh -A "root@$trajectory_host" -p "$trajectory_port"
    fi
}

# send satellites to a moon in a planet
function satellites {
    local planet=$1
    local moon=$2

    # sanity check
    if ! has_planet "$planet"; then
        ercho "error~ Planet: |$planet| does not exist!"
        return 1
    fi
    if ! has_moon "$planet" "$moon"; then
        ercho "error~ Moon: |$moon| does not exist for planet: |$planet|!"
        return 1
    fi

    # check if the moon we are trying to connect to is the current system
    if [[ "$moon" == "$(hostname)" ]]; then
        ercho "error~ Moon: |$moon| is the current system!"
    else
        local trajectory
        trajectory="$(get_trajectory "$planet" "$moon")"

        if [[ -z "$(jq -c -r '.' <<< "$trajectory")" ]]; then
            ercho "error~ Moon: |$moon| does not have a set trajectory!"
            return 1
        fi

        local trajectory_host trajectory_port
        trajectory_host="$(jq -c -r '.host' <<< "$trajectory")"
        trajectory_port="$(jq -c -r '.port' <<< "$trajectory")"

        echo "[solarsys] Moon: |$moon| is at |$trajectory_host| on port |$trajectory_port|"
        send_satellites "$planet" "$moon" "$trajectory_host" "$trajectory_port"
    fi
}

# lists planets and moons
function list {
    local planets
    readarray -t planets <<< "$(get_planets | jq -c -r '.[]')"

    for planet in "${planets[@]}"; do
        echo "$planet"

        local moons
        readarray -t moons <<< "$(get_moons "$planet" | jq -c -r '.[]')"

        for i in "${!moons[@]}"; do
            if [[ -z "${moons[i]}" ]]; then
                break
            fi

            local trajectory
            trajectory="$(get_trajectory "$planet" "${moons[i]}")"

            if [[ -z "$(jq -c -r '.' <<< "$trajectory")" ]]; then
                trajectory="{\"host\":\"localhost\",\"port\":0}"
            fi

            if [[ "$((i + 1))" == "${#moons[@]}" ]]; then
                echo "└───${moons[i]} at [$(jq -c -r '.host' <<< "$trajectory")]:$(jq -c -r '.port' <<< "$trajectory") orbits $(get_orbits "$planet" "${moons[i]}")"
            else
                echo "├───${moons[i]} at [$(jq -c -r '.host' <<< "$trajectory")]:$(jq -c -r '.port' <<< "$trajectory") orbits $(get_orbits "$planet" "${moons[i]}")"
            fi
        done

        echo
    done
}

# returns json of planets and moons
function json {
    local planets
    readarray -t planets <<< "$(get_planets | jq -c -r '.[]')"

    local planets_json
    planets_json="$(for planet in "${planets[@]}"; do
        jq -c -r -n --argjson ms "$(get_moons "$planet")" "{""$planet"": \$ms}"
    done)"
    jq -c -r -s add <<< "$planets_json"
}

# prints usage of solarsys
function print_usage {
    ercho "Usage: $0 <subcommand>"
    ercho
    ercho "  Subcommand                     |  Description"
    ercho "--------------------------------------------------------------------------"
    ercho "  deploy <planet> <moon>         |  Deploys <moon> in <planet>"
    ercho "  build <planet> <moon> <output> |  Builds <output> for <moon> in <planet>"
    ercho "  rollback <planet> <moon>       |  Rolls back <moon> in <planet>"
    ercho "  test <planet> <moon>           |  Tests <moon> in <planet>"
    ercho "  ssh <planet> <moon>            |  SSH to <moon> in <planet>"
    ercho "  satellites <planet> <moon>     |  Send satellites to <moon> in <planet>"
    ercho "  update                         |  Updates and commits flake.lock"
    ercho "  list                           |  Lists planets and moons"
    ercho "  json                           |  Returns json of planets and moons"
    exit 1
}

# main function
function main {
    # check if subcommand is set
    local subcommand=$1
    if [[ -z "$subcommand" ]]; then
        print_usage
    fi

    # switch on subcommand
    case "$subcommand" in
        deploy)
            local planet=$2
            local moon=$3
            if [[ -z "$planet" ]] || [[ -z "$moon" ]]; then
                ercho "error~ No planet and/or moon specified"
                ercho
                print_usage
            fi

            deploy "$planet" "$moon"
            ;;
        build)
            local planet=$2
            local moon=$3
            local output=$4
            if [[ -z "$planet" ]] || [[ -z "$moon" ]] || [[ -z "$output" ]]; then
                ercho "error~ No planet, moon, and/or output specified"
                ercho
                print_usage
            fi

            build "$planet" "$moon" "$output"
            ;;

        rollback)
            local planet=$2
            local moon=$3
            if [[ -z "$planet" ]] || [[ -z "$moon" ]]; then
                ercho "error~ No planet and/or moon specified"
                ercho
                print_usage
            fi

            rollback "$planet" "$moon"
            ;;
        test)
            local planet=$2
            local moon=$3
            if [[ -z "$planet" ]] || [[ -z "$moon" ]]; then
                ercho "error~ No planet and/or moon specified"
                ercho
                print_usage
            fi

            test_moon "$planet" "$moon"
            ;;
        ssh)
            local planet=$2
            local moon=$3
            if [[ -z "$planet" ]] || [[ -z "$moon" ]]; then
                ercho "error! No planet and/or moon specified"
                ercho
                print_usage
            fi

            ssh_moon "$planet" "$moon"
            ;;
        satellites)
            local planet=$2
            local moon=$3
            if [[ -z "$planet" ]] || [[ -z "$moon" ]]; then
                ercho "error! No planet and/or moon specified"
                ercho
                print_usage
            fi

            satellites "$planet" "$moon"
            ;;
        update)
            nix flake update --commit-lock-file
            ;;
        list)
            list
            ;;
        json)
            json
            ;;
        *)
            ercho "error~ Unknown subcommand: $subcommand"
            ercho
            print_usage
            ;;
    esac
}

# run main
main "$@"
