#!/usr/bin/env bash

# Use the "logo" key as the primary modifier
mod="Mod4"

# Normal mode applications
riverctl map normal $mod Return          spawn kitty
riverctl map normal $mod D               spawn wofi --show drun
riverctl map normal Control+Mod1 Space   spawn makoctl dismiss
riverctl map normal Control+Shift Space  spawn makoctl restore
riverctl map normal None Print           spawn "bash -c \"grim -g '$(slurp)' - | wl-copy -t 'image/png'\""

# Mod+Q to close the focused view
riverctl map normal $mod Q close

# Mod+Shift+Q to exit river
riverctl map normal $mod+Shift Q exit

# Mod+J and Mod+K to focus the next/previous view in the layout stack
riverctl map normal $mod J focus-view next
riverctl map normal $mod K focus-view previous

# Mod+Shift+J and Mod+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal $mod+Shift J swap next
riverctl map normal $mod+Shift K swap previous

# Mod+Period and Mod+Comma to focus the next/previous output
riverctl map normal $mod Period focus-output next
riverctl map normal $mod Comma focus-output previous

# Mod+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal $mod+Shift Period send-to-output next
riverctl map normal $mod+Shift Comma send-to-output previous

# Mod+Return to bump the focused view to the top of the layout stack
riverctl map normal $mod Tab zoom

# Mod+H and Mod+L to decrease/increase the main_factor value of rivertile by 0.05
riverctl map normal $mod H mod-layout-value rivertile fixed main_factor -0.05
riverctl map normal $mod L mod-layout-value rivertile fixed main_factor +0.05

# Mod+Shift+H and Mod+Shift+L to increment/decrement the main_count value of rivertile.
riverctl map normal $mod+Shift H mod-layout-value rivertile int main_count +1
riverctl map normal $mod+Shift L mod-layout-value rivertile int main_count -1

# Mod + Left Mouse Button to move views
riverctl map-pointer normal $mod BTN_LEFT move-view

# Mod + Right Mouse Button to resize views
riverctl map-pointer normal $mod BTN_RIGHT resize-view

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Mod+[1-9] to focus tag [0-8]
    riverctl map normal $mod $i set-focused-tags $tags

    # Mod+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal $mod+Shift $i set-view-tags $tags

    # Mod+Ctrl+[1-9] to toggle focus of tag [0-8]
    riverctl map normal $mod+Control $i toggle-focused-tags $tags

    # Mod+Shift+Ctrl+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal $mod+Shift+Control $i toggle-view-tags $tags
done

# Mod+0 to focus all tags
# Mod+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal $mod 0 set-focused-tags $all_tags
riverctl map normal $mod+Shift 0 set-view-tags $all_tags

# Mod+S to toggle float
riverctl map normal $mod S toggle-float

# Mod+F to toggle fullscreen
riverctl map normal $mod F toggle-fullscreen

# Mod+{Up,Right,Down,Left} to change layout orientation
riverctl map normal $mod Up    set-layout-value rivertile string main_location top
riverctl map normal $mod Right set-layout-value rivertile string main_location right
riverctl map normal $mod Down  set-layout-value rivertile string main_location bottom
riverctl map normal $mod Left  set-layout-value rivertile string main_location left

# Passthrough mode
riverctl declare-mode passthrough
riverctl map normal $mod G enter-mode passthrough
riverctl map passthrough $mod G enter-mode normal

# Mappings for all modes
for mode in normal locked
do
    riverctl map $mode None XF86AudioRaiseVolume  spawn pamixer -i 1
    riverctl map $mode None XF86AudioLowerVolume  spawn pamixer -d 1
    riverctl map $mode None XF86AudioMute         spawn pamixer -t

    riverctl map $mode None XF86AudioPrev     spawn mpc prev
    riverctl map $mode None XF86AudioNext     spawn mpc next
    riverctl map $mode None XF86AudioPlay     spawn mpc toggle
done

# Set repeat rate
riverctl set-repeat 50 300

# Set app-ids of views which should float
riverctl float-filter-add "float"
riverctl float-filter-add "popup"

# Set opacity and fade effect
# riverctl opacity 1.0 0.75 0.0 0.1 20

# Run applications
systemctl --user import-environment
dbus-update-activation-environment 2>/dev/null && dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

systemctl --user restart kdeconnect.service
systemctl --user restart kdeconnect-indicator.service
systemctl --user restart syncthing.service
systemctl --user restart mpdris2.service
systemctl --user restart pipewire.socket
systemctl --user restart xdg-desktop-portal.service

waybar &
mako &
oguri &

# Jump to rivertile
riverctl default-layout rivertile
exec rivertile
